// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = const FirebaseOptions(
    apiKey: 'AIzaSyB6XepDO9qiess4bWicHkTt20njm7VxGJ4',
    appId: '1:560661942368:web:a5d3db8fcff704a2147305',
    messagingSenderId: '560661942368',
    projectId: 'shop-app-63f61',
    authDomain: 'shop-app-63f61.firebaseapp.com',
    databaseURL:
        'https://shop-app-63f61-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'shop-app-63f61.appspot.com',
    measurementId: 'G-2V1TG6MQVF',
  );

  static const FirebaseOptions android = const FirebaseOptions(
    apiKey: 'AIzaSyCkHdcJZ_lYKQjnExHUbl3495FJJJUljxI',
    appId: '1:560661942368:android:279ad444b2fae4d0147305',
    messagingSenderId: '560661942368',
    projectId: 'shop-app-63f61',
    databaseURL:
        'https://shop-app-63f61-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'shop-app-63f61.appspot.com',
  );

  static const FirebaseOptions ios = const FirebaseOptions(
    apiKey: 'AIzaSyCha07hi3mnSg-c4d6LqSYEE2j_lLd-LSk',
    appId: '1:560661942368:ios:8818134fb8e79259147305',
    messagingSenderId: '560661942368',
    projectId: 'shop-app-63f61',
    databaseURL:
        'https://shop-app-63f61-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'shop-app-63f61.appspot.com',
    iosClientId:
        '560661942368-o9bllm2lmnvkb5nthj0bvlbu66b1or8g.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopApp',
  );
}
